13_encrypt.o: 13_encrypt.c
	gcc -c 13_encrypt.c
13_message_hider.o: 13_message_hider.c
	gcc -c 13_message_hider.c
a.out: 13_encrypt.o 13_message_hider.o
	gcc 13_encrypt.o 13_message_hider.o -o a.out

